### PR TITLE
:sparkles: Realize a true IME

### PR DESCRIPTION
**Pull request by Freed-Wu**
Realize a real IME.

screen-2024-06-24-21-34-21

register an autocmd to:

1. capture input character
2. pass it to librime
3. get context
4. destroy the previous window (if existed)
5. draw new window

And an autocmd to

1. trigger when exit insert mode
2. destroy the previous window (if existed)

Refer:

- https://github.com/tonyfettes/fcitx5.nvim
- https://github.com/black-desk/fcitx5-ui.nvim

Related:

- https://github.com/neoclide/coc.nvim/discussions/5053
- https://github.com/neoclide/coc.nvim/discussions/5054

### CODE REVIEW

**Comment by tonyfettes** [comment]
Nice work! Never though this is possible within coc.nvim.

By the way, do you mind if I transfer the project to you. I don't think I'm qualified to be a maintainer of the repository now, so I guess it might be better to move it under your name...

**Comment by Freed-Wu** [comment]
No serious. It depends on you :smile:

**Comment by Freed-Wu** [comment]
Not it works!

> this is possible within coc.nvim

I list some limitaion in README. Some is unresolved due to coc.nvim.

> transfer the project to you

Yes, github CI/CD needs `NODE_AUTH_TOKEN` to upload new version to npm. Else it will fail:

https://github.com/tonyfettes/coc-rime/actions/runs/9723174282/job/26837970342

**Comment by tonyfettes** [comment]
@Freed-Wu I started the transfer, can you please check the email to see if you get any GitHub email on the transfer?

**Comment by Freed-Wu** [comment]
Thanks!

**Pull request merged**
